stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.10
  before_script:
    - pip install black isort
  script:
    - black --check .
    - isort --check .

test:
  stage: test
  image: python:3.10
  before_script:
    - apt-get update
    - apt-get install -y libxcb-xinerama0
    - apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libgl1-mesa-glx
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -e .
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - report.xml
