LOADSCREEN_IMAGE = "Panda.png.jpg"
COLOUR = "#BE632E"
GIT = "https://git.scicore.unibas.ch/zavolan_group/teaching_and_tutorials/pls-2024-group-c"
RELEASES = "https://en.wikipedia.org/wiki/Red_panda#/media/File:Tiergarten_Schoenbrunn_Kleiner_Panda_2.jpg"
DOCUMENTATION = "https://en.wikipedia.org/wiki/Red_panda"
